const STRING_CONSTANTS = {
  EMAIL_NOT_VALID: 'Provided email is not valid',

  BUCKET_DETAILS: 'BucketDetails',
  DRAG_AND_DROP: 'DragAndDrop',
  // ACTION CONSTANTS
  FETCH_DASHBOARD_DATA: 'FETCH_DASHBOARD_DATA',
  TOGGLE_DASHBOARD_VIEW: 'TOGGLE_DASHBOARD_VIEW',
  SET_DASHBOARD_DATA: 'SET_DASHBOARD_DATA',
  DRAG_ELEMENT_DROPPED: 'DRAG_ELEMENT_DROPPED',
  SAVE_FEEDBACK: 'SAVE_FEEDBACK',
  USER_FEEDBACKS: 'USER_FEEDBACKS',

  // IMAGE PATHS
  HAMBURGER_MENU: '/internals/assets/images/hamburger_menu.svg',
};


export { STRING_CONSTANTS };
